"""Add ConsultantTimeSlot model and update Booking model2

Revision ID: fc162b10c2ce
Revises: b42f7418e3c3
Create Date: 2025-06-22 14:44:06.895288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc162b10c2ce'
down_revision = 'b42f7418e3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultants', schema=None) as batch_op:
        batch_op.drop_column('employment_type')

    # ### end Alembic commands ###
